/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UGlassWrapper: typeof import('./../../components/01.kit/UGlassWrapper/index.ts')['default']
    UIcon: typeof import('./../../components/01.kit/UIcon/index.ts')['default']
    UMarker: typeof import('./../../components/01.kit/UMarker/index.ts')['default']
  }
}
